I'm sorry, but errors were detected in your script. Please correct the
errors listed below, and try again.


The label _call_hall_26 is defined twice, at
  File "game/day4.rpy", line 302 and
  File "game/day4.rpy", line 312.

Ren'Py Version: Ren'Py 6.99.13.2919
